import type { Metadata, Viewport } from "next";
import { getAboutCompany, getServiceCategory, getServiceContent } from "./actions";
import "../app/css/global.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	initialScale: 1,
	width: "device-width",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const aboutCompany = await getAboutCompany();

	return (
		<html lang="en">
			<body className="antialiased">
				<Navbar logo={aboutCompany.logo.url} />
				{children}
			</body>
		</html>
	);
}
